### ISSUE TITLE
Export: General Information Section

### ISSUE THREAD

**Issue by rekt-hard** [tuwien-csd/damap-backend#131]
The DMP version must be entered manually under "Administrative information". An additional description is also added without further comment.
![image](https://github.com/tuwien-csd/damap-backend/assets/72449192/5e567f10-79a5-4180-89dc-c93df18d038d)

**Comment by ChristianeStork** [comment]
See also frontend #101

**Comment by ValentinFutterer** [comment]
After consultation with Christiane and Tomasz:
The version listed here is not supposed to be the same as the versions that are saved in DAMAP - altough this is easy to misunderstand.

**Comment by ChristianeStork** [comment]
Several DAMAP versions (drafts) may be needed to produce the particular version that will be sent to the funder (FWF in this case) as version 1.0 of the DMP. Since the tool is currently mainly (if not exclusively) used to produce this first version, I would set the version number in the DMP template to "1.0" by default. It can later be changed in the word doc if requiered.

**Comment by rekt-hard** [comment]
Understood.
How about highlighting the version placeholder here with green, as is done with other placeholders? This will signal, that manual action is required.

**Comment by ChristianeStork** [comment]
Perfect!
