### ISSUE TITLE
Support connection to Invenio RDM

### ISSUE THREAD

**Issue by ZenoLC** [tuwien-csd/damap-backend#48]

**Comment by DerekMolnar** [comment]
From the December 19, 2023 Product Owner meeting:
o	A stable InvenioRDM connection should be completed in Q1 2024, future interoperability with other data-set repositories can be pursued once this is completed

**Comment by rekt-hard** [comment]
In this generic implementation, it should be possible to implement a custom workflow. In order to get the correct user id from DAMAP, a user may have to authenticate themself. Both systems could use the same identity provider but it is not certain.

Here are two possible scenarios:
- Both systems use the same identity provider. The user id used in DAMAP is also stored in the InvenioRDM database (i.e. `extra_data` field in the `oauthclient_remoteaccount` table). When fetching the user id, a simple database lookup within InvenioRDM is enough.
- The systems use a different identity provider. A user has to authenticate in DAMAP and the user id will be returned. This can be achieved via an oauth workflow, in which a token containing the user id is returned to InvenioRDM.

The generic solution should allow to realize both scenarios.
